# Generated by Django 3.1.7 on 2021-03-23 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_robots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('allowed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('group', models.ManyToManyField(through='seo.Rule', to='seo.URL')),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.useragent'),
        ),
        migrations.AddField(
            model_name='rule',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.url'),
        ),
    ]
