# Generated by Django 3.1.7 on 2021-03-23 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_auto_20210323_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useragent',
            name='group',
        ),
        migrations.AddField(
            model_name='rule',
            name='robot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seo.robot'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('robot', 'agent', 'url', 'allowed')},
        ),
        migrations.RemoveField(
            model_name='rule',
            name='name',
        ),
    ]
