# Generated by Django 3.1.7 on 2021-03-23 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_auto_20210323_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.DeleteModel(
            name='Key',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
