# Generated by Django 3.1.7 on 2021-03-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0006_auto_20210323_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='slug',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='useragent',
            name='value',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
